### ISSUE TITLE
Make carousel better

### ISSUE THREAD

**Issue by theritiktiwari** [codingwalls/hacktoberfest-web#19]
## Changes to be made

- Make the background a lil dark so the text will be visible.
- Make the images height 100%.

`Use Bootstrap 5`

**Comment by jawariaalvi32** [comment]
Hey @theritiktiwari . I want to work on this. Please assign me this.

**Comment by abhinavagarwal-web** [comment]
Hey, Can I work on this issue

**Comment by theritiktiwari** [comment]
> Hey, Can I work on this issue

Yeah sure
