### ISSUE TITLE
Add Carousel in Home Page

### ISSUE THREAD

**Issue by theritiktiwari** [codingwalls/hacktoberfest-web#2]
## USE BOOTSTRAP

**Comment by Prakarsh-Kaushik** [comment]
I'm interested in helping you with this. How may I help you?

**Comment by theritiktiwari** [comment]
Make a carousel of minimum 5 items and use dummy data for home page

**Comment by Prakarsh-Kaushik** [comment]
Pull request created. Kindly check

**Comment by theritiktiwari** [comment]
Carousel is not okay and made some other problems in the styling

**Comment by Prakarsh-Kaushik** [comment]
Can you please explain your requirements? So I can make the changes accordingly?

**Comment by theritiktiwari** [comment]
## Requirements

- Use bootstrap
- Made in complete page
- Background color is same as website only images will be added (full screen cover with images)
- use different images [check for unsplash API (search source unsplash)]

And you are good to go.


`You made some errors, it changed other page styling too`

**Comment by Prakarsh-Kaushik** [comment]
> ## Requirements
> * Use bootstrap
> * Made in complete page
> * Background color is same as website only images will be added (full screen cover with images)
> * use different images [check for unsplash API (search source unsplash)]
> 
> And you are good to go.
> 
> `You made some errors, it changed other page 


# Is this ok?
![After1](https://user-images.githubusercontent.com/63556277/135929090-d0492c10-5221-49c0-8d9d-cf87bd08ccce.jpg)
styling too`

**Comment by theritiktiwari** [comment]
uhm!! Firstly use Bootstrap 5 (else the styling differ in some elements)
then use a API not only 5 images (like it will change every time when you refresh the page)
Here is the link (https://source.unsplash.com/1600x900/?nature,water) Change the keyword (nature and water)
Other than all good.
