### ISSUE TITLE
Add Contact Us Page

### ISSUE THREAD

**Issue by theritiktiwari** [codingwalls/hacktoberfest-web#5]
## use Bootstrap

**Comment by sajdakabir** [comment]
Hey @theritiktiwari i'm interested to doing it could you please assign it to me?

**Comment by sajdakabir** [comment]
hey @theritiktiwari  it's done can you check it please

**Comment by agungjsp** [comment]
Hi, @theritiktiwari is that possible for you to open this issue again?
I just finished the contact us page, forgot to ask you to assign me this issue

**Comment by theritiktiwari** [comment]
> Hi, @theritiktiwari is that possible for you to open this issue again? I just finished the contact us page, forgot to ask you to assign me this issue

Very happy to see that you wanna work but contact page is designed now. If you want to work then make it better and make PR.
