### ISSUE TITLE
Add About Us Page

### ISSUE THREAD

**Issue by theritiktiwari** [codingwalls/hacktoberfest-web#6]

**Comment by nishantkumar1308** [comment]
please assign it to me

**Comment by theritiktiwari** [comment]
> please assign it to me

It's done already. You can make some changes and make that more beautiful

**Comment by nishantkumar1308** [comment]
I am beginner  in open source and try to make it more beautiful .

Question: Is this repo really counting for Hacktoberfest 2021?
